name: Test

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  scratch:
    name: Scratch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: echo test
