name: Test

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  scratch:
    name: Scratch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - run: |
          test=$(echo test)
          echo "TEST_ENV=${test}" >> "$GITHUB_ENV"

      - run: gh auth status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
